use anyhow::Result;
use syn::{Meta, Token, punctuated::Punctuated};
use typify::{TypeSpace, TypeSpaceSettings};

pub fn generate(schema: &str) -> Result<String> {
    let root = serde_json::from_str::<schemars::schema::RootSchema>(schema)?;
    let mut settings = TypeSpaceSettings::default();
    settings
        .with_struct_builder(false)
        .with_map_type("::std::collections::BTreeMap")
        .with_derive("PartialEq".to_owned());
    let mut type_space = TypeSpace::new(&settings);
    type_space.add_ref_types(root.definitions)?;
    let mut syntax = syn::parse2::<syn::File>(type_space.to_stream())?;
    keep_default_values_when_serializing(&mut syntax)?;
    implement_cpp_empty_object_semantics(&mut syntax)?;
    let mut output = String::from("// @generated by `cargo xtask generate`; do not edit.\n\n");
    output.push_str(&prettyplease::unparse(&syntax));
    Ok(output)
}

/// WSL's hand-written `EmptyObject` decoder accepts and ignores any JSON value,
/// while its encoder always emits `{}`. Mirror that behavior instead of
/// Typify's stricter empty-struct implementation.
fn implement_cpp_empty_object_semantics(file: &mut syn::File) -> Result<()> {
    let empty_object = file.items.iter_mut().find_map(|item| match item {
        syn::Item::Struct(item) if item.ident == "EmptyObject" => Some(item),
        _ => None,
    });
    let Some(empty_object) = empty_object else {
        anyhow::bail!("generated schema has no EmptyObject type");
    };

    empty_object
        .attrs
        .retain(|attribute| !attribute.path().is_ident("serde"));
    for attribute in &mut empty_object.attrs {
        if !attribute.path().is_ident("derive") {
            continue;
        }
        let derives = attribute
            .parse_args_with(Punctuated::<syn::Path, Token![,]>::parse_terminated)?
            .into_iter()
            .filter(|path| {
                !path.segments.last().is_some_and(|segment| {
                    segment.ident == "Serialize" || segment.ident == "Deserialize"
                })
            })
            .collect::<Punctuated<_, Token![,]>>();
        *attribute = syn::parse_quote!(#[derive(#derives)]);
    }

    file.items.push(syn::parse_quote! {
        impl ::serde::Serialize for EmptyObject {
            fn serialize<S>(&self, serializer: S) -> ::std::result::Result<S::Ok, S::Error>
            where
                S: ::serde::Serializer,
            {
                let map = serializer.serialize_map(Some(0))?;
                ::serde::ser::SerializeMap::end(map)
            }
        }
    });
    file.items.push(syn::parse_quote! {
        impl<'de> ::serde::Deserialize<'de> for EmptyObject {
            fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
            where
                D: ::serde::Deserializer<'de>,
            {
                let _ = <::serde::de::IgnoredAny as ::serde::Deserialize>::deserialize(deserializer)?;
                Ok(Self {})
            }
        }
    });
    Ok(())
}

/// nlohmann's intrusive macro serializes every declared member. Typify normally
/// omits values that equal their JSON Schema default, so remove only those
/// serialization guards while retaining `default` for compatible decoding.
fn keep_default_values_when_serializing(file: &mut syn::File) -> Result<()> {
    for item in &mut file.items {
        let syn::Item::Struct(item) = item else {
            continue;
        };
        for field in &mut item.fields {
            for attribute in &mut field.attrs {
                if !attribute.path().is_ident("serde") {
                    continue;
                }
                let mut options =
                    attribute.parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated)?;
                options = options
                    .into_iter()
                    .filter(|option| !option.path().is_ident("skip_serializing_if"))
                    .collect();
                *attribute = syn::parse_quote!(#[serde(#options)]);
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_fields_are_never_skipped_when_serializing() {
        let schema = include_str!("../../wslc_schema_rs/generated/wslc_schema.schema.json");
        let rust = generate(schema).unwrap();
        assert!(!rust.contains("skip_serializing_if"));
        assert!(rust.contains("default"));
    }
}
